version: "3.8"

services:
  db:
    image: postgres:15
    container_name: employee_management_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_management
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employee_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./employeeManagement
      dockerfile: Dockerfile
    container_name: employee_management_backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TOKEN_KEY: ${TOKEN_KEY}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./employeePortal
      dockerfile: Dockerfile
    container_name: employee_management_frontend
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://localhost:8081
    depends_on:
      - backend

volumes:
  db_data: